-- Quick.ai Supabase schema
-- Run this in the Supabase SQL editor for project ref: vncmddxwzobfiqnwoubx

create table if not exists public.creations (
  id bigint generated by default as identity primary key,
  user_id text not null,
  prompt text not null,
  content text not null,
  type text not null,
  publish boolean not null default false,
  likes text[] not null default '{}'::text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists creations_user_id_idx on public.creations (user_id);
create index if not exists creations_publish_idx on public.creations (publish);
create index if not exists creations_type_idx on public.creations (type);
create index if not exists creations_created_at_idx on public.creations (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists creations_set_updated_at on public.creations;
create trigger creations_set_updated_at
before update on public.creations
for each row
execute function public.set_updated_at();

alter table public.creations enable row level security;
